# -*- coding: utf-8 -*-
"""Single source of truth for the Jalvin Fresh catalogue.

Both data/products.json and the SVG illustrations are generated from this list,
so a product can never exist without a picture or vice versa.

Fields:
  id       filename-safe key, also the SVG filename
  ms/en    bilingual name (Malay first - this is a Malaysian shop)
  cat      sayur | ikan | ayam | nonhalal
  pack     what the customer actually receives - never hide the weight
  price    selling price in RM
  cost     what it costs at the farm/market (admin only, drives margin display)
  cap      max units sellable per delivery cycle (your cash + boot space)
  art      (archetype, params) for the illustration generator
  note     one short honest line shown on the product card
"""

P = [
    # ---------------- SAYUR / VEGETABLES ----------------
    ("kangkung", "Kangkung", "Water Spinach", "sayur", "1 ikat ≈ 250g", 2.50, 1.80, 40,
     ("leafy", dict(leaf="#3E8E4F", dark="#2C6B3A", stem="#7FB069", n=5, slim=True)),
     "Young and crisp — the one for goreng belacan."),
    ("bayam", "Bayam Merah", "Red Spinach", "sayur", "1 ikat ≈ 250g", 2.80, 2.00, 35,
     ("leafy", dict(leaf="#8E3B52", dark="#6B2A3D", stem="#A8546A", n=5, slim=False)),
     "Sweet and tender. Wilts fast — cook within two days."),
    ("sawi", "Sawi Hijau", "Green Mustard", "sayur", "1 ikat ≈ 300g", 3.00, 2.20, 35,
     ("leafy", dict(leaf="#4A9B4E", dark="#357238", stem="#B9D98A", n=4, slim=False)),
     "Mild and juicy. Good in soup or a quick stir-fry."),
    ("kailan", "Kailan", "Chinese Kale", "sayur", "1 ikat ≈ 250g", 3.50, 2.50, 30,
     ("leafy", dict(leaf="#2F7A45", dark="#205731", stem="#6FA85C", n=4, slim=False)),
     "Thick stems, deep green leaves. Blanch then oyster sauce."),
    ("choysum", "Choy Sum", "Flowering Cabbage", "sayur", "1 ikat ≈ 300g", 3.20, 2.30, 30,
     ("leafy", dict(leaf="#55A34B", dark="#3B7B3E", stem="#9CC86B", n=4, slim=False)),
     "Picked with the yellow flowers still on — that's how you know it's fresh."),
    ("terung", "Terung", "Brinjal / Eggplant", "sayur", "3 biji ≈ 500g", 4.50, 3.20, 25,
     ("oblong", dict(body="#6B4C8A", dark="#4E3567", top="#4A8B3F", curve=0.9)),
     "Long purple variety. Perfect for sambal terung."),
    ("bendi", "Bendi", "Okra / Lady's Finger", "sayur", "1 pek ≈ 300g", 4.00, 2.80, 25,
     ("pod", dict(body="#5FA04A", dark="#437833", n=5, ridged=True, length=1.0)),
     "Hand-picked young — snap the tip, it should break clean."),
    ("timun", "Timun", "Cucumber", "sayur", "3 biji ≈ 600g", 3.50, 2.50, 30,
     ("oblong", dict(body="#4E9B57", dark="#37753F", top="#77B26A", curve=1.15)),
     "Cool and crunchy. Great for ulam and salad."),
    ("tomato", "Tomato", "Tomato", "sayur", "1 pek ≈ 500g", 5.00, 3.60, 30,
     ("round", dict(body="#D6413C", dark="#A82F2B", top="#4A8B3F", n=3)),
     "Firm, ripe, not watery. Cameron Highlands stock."),
    ("cili-merah", "Cili Merah", "Red Chilli", "sayur", "1 pek ≈ 200g", 5.50, 4.00, 25,
     ("chili", dict(body="#CC2F2F", dark="#9B2020", stem="#4A8B3F", n=4, small=False)),
     "For sambal, kuah and rempah."),
    ("cili-padi", "Cili Padi", "Bird's Eye Chilli", "sayur", "1 pek ≈ 100g", 6.00, 4.50, 20,
     ("chili", dict(body="#D94A2B", dark="#A43318", stem="#4A8B3F", n=7, small=True)),
     "Properly hot. Handle with respect."),
    ("bawang-besar", "Bawang Besar", "Big Onion", "sayur", "1 kg", 6.50, 4.80, 30,
     ("bulb", dict(body="#C98A4B", dark="#9E6733", top="#B9A05C", n=3, papery=True)),
     "India stock. Keeps two weeks in a cool dry spot."),
    ("bawang-merah", "Bawang Merah", "Shallot", "sayur", "1 pek ≈ 500g", 8.00, 6.00, 25,
     ("bulb", dict(body="#A8547A", dark="#7E3A58", top="#8E7A4C", n=5, papery=True)),
     "The base of almost every Malay dish."),
    ("bawang-putih", "Bawang Putih", "Garlic", "sayur", "1 pek ≈ 500g", 9.00, 6.80, 25,
     ("bulb", dict(body="#EFE6D6", dark="#C9BCA6", top="#B9A05C", n=3, papery=True)),
     "Plump cloves, tight skin, no green shoots."),
    ("halia", "Halia", "Ginger", "sayur", "1 pek ≈ 250g", 4.50, 3.20, 25,
     ("root", dict(body="#D4B278", dark="#A88B52", knobs=True)),
     "Old ginger — stronger heat, better for masak."),
    ("kentang", "Kentang", "Potato", "sayur", "1 kg", 5.50, 4.00, 30,
     ("root", dict(body="#D9B67E", dark="#AE8C58", knobs=False)),
     "All-rounder. Curry, soup, goreng — works in all of them."),
    ("lobak-merah", "Lobak Merah", "Carrot", "sayur", "1 kg", 5.00, 3.60, 30,
     ("carrot", dict(body="#E07B2C", dark="#B05C18", top="#4A8B3F")),
     "Sweet and firm, tops trimmed so they last longer."),
    ("kobis", "Kobis", "Cabbage", "sayur", "1 biji ≈ 800g", 4.50, 3.20, 25,
     ("cabbage", dict(body="#C6D9A8", dark="#9DB47E", vein="#E4EED2")),
     "Tight and heavy for its size — that's a good one."),
    ("taugeh", "Taugeh", "Bean Sprouts", "sayur", "1 pek ≈ 300g", 2.50, 1.70, 30,
     ("sprouts", dict(body="#F0EAD6", dark="#CFC5A8", tip="#D7C44E")),
     "Cleaned and tailed for you. Use the same day."),
    ("petai", "Petai", "Stink Bean", "sayur", "1 papan (≈10 pods)", 12.00, 9.00, 15,
     ("pod", dict(body="#7FA83C", dark="#5C7D26", n=3, ridged=False, length=1.4)),
     "In season and fat. Sambal petai udang, no argument."),
    ("ubi-keledek", "Ubi Keledek", "Sweet Potato", "sayur", "1 kg", 5.50, 4.00, 25,
     ("root", dict(body="#C2703F", dark="#95522A", knobs=False)),
     "Orange flesh, naturally sweet. Steam or bake."),
    ("labu", "Labu", "Pumpkin", "sayur", "1 potong ≈ 700g", 5.00, 3.50, 20,
     ("round", dict(body="#E09030", dark="#B06C1C", top="#4A8B3F", n=1, ribbed=True)),
     "Cut fresh on the day, wrapped and chilled."),
    ("peria", "Peria", "Bitter Gourd", "sayur", "2 biji ≈ 400g", 4.50, 3.20, 20,
     ("pod", dict(body="#6DA33C", dark="#3F6B1E", n=2, ridged=True, warty=True, length=1.25)),
     "Bitter, and that's the point. Good with egg."),
    ("kacang-panjang", "Kacang Panjang", "Long Bean", "sayur", "1 ikat ≈ 300g", 3.50, 2.50, 30,
     ("longbean", dict(body="#5D9E3E", dark="#41762A")),
     "Snappy and tender. Masak lemak or sambal."),
    ("serai", "Serai", "Lemongrass", "sayur", "5 batang", 2.50, 1.60, 30,
     ("lemongrass", dict(body="#B9CC8A", dark="#8EA463", leaf="#5D9E3E")),
     "Fat stalks with plenty of white at the base."),
    ("cendawan-tiram", "Cendawan Tiram", "Oyster Mushroom", "sayur", "1 pek ≈ 200g", 5.00, 3.50, 20,
     ("mushroom", dict(body="#D8CBB0", dark="#A08F73", stem="#EDE4D4")),
     "Locally grown. Meaty texture, great for vegetarians."),
    ("jagung", "Jagung Manis", "Sweet Corn", "sayur", "3 batang", 6.00, 4.20, 25,
     ("corn", dict(body="#F0C93F", dark="#C9A01F", husk="#6FA85C")),
     "Husk left on to keep the kernels juicy."),

    # ---------------- IKAN / FISH & SEAFOOD ----------------
    ("ikan-kembung", "Ikan Kembung", "Indian Mackerel", "ikan", "≈ 500g (4–5 ekor)", 16.00, 12.00, 25,
     ("fish", dict(body="#9BB3C4", dark="#6E8798", belly="#EDF2F5", stripe="#54697A", shape=1.0)),
     "The everyday fish. Goreng garing or masak asam."),
    ("ikan-selar", "Ikan Selar", "Yellowstripe Scad", "ikan", "≈ 500g", 14.00, 10.50, 25,
     ("fish", dict(body="#C4C09B", dark="#98946E", belly="#F2F0E4", stripe="#D7C44E", shape=0.9)),
     "Small, sweet, and made for deep-frying whole."),
    ("ikan-cencaru", "Ikan Cencaru", "Torpedo Scad", "ikan", "≈ 500g (2–3 ekor)", 18.00, 13.50, 20,
     ("fish", dict(body="#A9B8B0", dark="#7B8A82", belly="#EFF3F0", stripe="#5E6E66", shape=1.15)),
     "Firm flesh. Stuff it with sambal and grill."),
    ("ikan-tenggiri", "Ikan Tenggiri", "Spanish Mackerel", "ikan", "≈ 400g (steak cut)", 28.00, 22.00, 15,
     ("fishsteak", dict(body="#D9CFC4", dark="#A8998A", bone="#F2ECE4", skin="#6E8798")),
     "Cut into steaks. The proper fish for gulai and otak-otak."),
    ("ikan-bawal", "Ikan Bawal Putih", "White Pomfret", "ikan", "≈ 400g (1 ekor)", 32.00, 25.00, 12,
     ("fish", dict(body="#E0E4E8", dark="#B0B8C0", belly="#F7F9FA", stripe="#9AA5AE", shape=0.75)),
     "Delicate and sweet. Steam it simply with ginger."),
    ("ikan-siakap", "Ikan Siakap", "Barramundi", "ikan", "≈ 600g (1 ekor)", 24.00, 18.00, 15,
     ("fish", dict(body="#B8C6CE", dark="#8A98A0", belly="#F0F4F6", stripe="#6E7C84", shape=1.05)),
     "Cleaned and scaled. Steam with soy or three-flavour sauce."),
    ("ikan-keli", "Ikan Keli", "Catfish", "ikan", "≈ 600g (2 ekor)", 12.00, 8.50, 20,
     ("fish", dict(body="#6E6152", dark="#4C4136", belly="#C9BCA6", stripe="#3A3128", shape=1.2, whiskers=True)),
     "Fresh from the pond. Masak lemak cili api."),
    ("ikan-tilapia", "Ikan Tilapia", "Tilapia", "ikan", "≈ 600g (1–2 ekor)", 14.00, 10.00, 20,
     ("fish", dict(body="#8E9B7C", dark="#68745A", belly="#E4E9DA", stripe="#525C46", shape=1.0)),
     "Clean-tasting freshwater fish. Good grilled."),
    ("sotong", "Sotong", "Squid", "ikan", "≈ 500g", 26.00, 20.00, 15,
     ("squid", dict(body="#F0DCD4", dark="#C9A79C", spot="#D98878")),
     "Cleaned, ink sac removed. Sambal sotong or goreng tepung."),
    ("udang-putih", "Udang Putih", "White Prawn", "ikan", "≈ 500g", 28.00, 22.00, 15,
     ("prawn", dict(body="#F2C2A8", dark="#CE9273", stripe="#D98060", size=1.0)),
     "Shell-on to keep the sweetness in."),
    ("udang-harimau", "Udang Harimau", "Tiger Prawn", "ikan", "≈ 500g", 45.00, 36.00, 10,
     ("prawn", dict(body="#E8B49C", dark="#B8775C", stripe="#5A4038", size=1.25)),
     "Big ones. Grill with butter and garlic, nothing else."),
    ("ketam", "Ketam", "Mud Crab", "ikan", "≈ 800g (2 ekor)", 38.00, 30.00, 10,
     ("crab", dict(body="#C96A4A", dark="#9B4A2E", claw="#D98060")),
     "Live-caught, cleaned and chilled. Chilli crab weather."),
    ("kerang", "Kerang", "Cockles", "ikan", "≈ 1 kg", 10.00, 7.00, 20,
     ("shellfish", dict(body="#B08968", dark="#856244", line="#D9C0A0")),
     "Scrubbed clean. Boil briefly, dip in sambal."),

    # ---------------- AYAM HALAL / HALAL CHICKEN ----------------
    ("ayam-standard", "Ayam Standard", "Whole Chicken", "ayam", "≈ 1.6 kg (1 ekor)", 16.00, 12.50, 25,
     ("wholechicken", dict(body="#F0CCA8", dark="#A87E58", wing="#E0BA92")),
     "JAKIM-certified halal supplier. Cleaned and cut on request."),
    ("ayam-kampung", "Ayam Kampung", "Free-Range Chicken", "ayam", "≈ 1.2 kg (1 ekor)", 28.00, 22.00, 12,
     ("wholechicken", dict(body="#DFB786", dark="#8E6A42", wing="#CFA470")),
     "Firmer meat, deeper flavour. The one for soup and rendang."),
    ("dada-ayam", "Dada Ayam", "Chicken Breast", "ayam", "≈ 500g", 12.00, 9.00, 30,
     ("chickencut", dict(body="#F0CDB4", dark="#B98A6E", kind="breast")),
     "Boneless, skinless, trimmed. Meal-prep favourite."),
    ("peha-ayam", "Peha Ayam", "Chicken Thigh & Drumstick", "ayam", "≈ 600g", 13.00, 9.50, 30,
     ("chickencut", dict(body="#E8BFA4", dark="#AE7E62", kind="drum")),
     "Juicier than breast. Best for ayam goreng."),
    ("sayap-ayam", "Sayap Ayam", "Chicken Wings", "ayam", "≈ 500g", 11.00, 8.00, 25,
     ("chickencut", dict(body="#EDC7AC", dark="#B5876B", kind="wing")),
     "Whole wings, tips on. Grill or fry."),
    ("fillet-ayam", "Fillet Ayam", "Chicken Fillet", "ayam", "≈ 500g", 15.00, 11.50, 20,
     ("chickencut", dict(body="#F4D6C0", dark="#C09378", kind="fillet")),
     "Sliced thin, ready for the pan. Zero prep."),
    ("hati-pedal", "Hati & Pedal", "Liver & Gizzard", "ayam", "≈ 400g", 8.00, 5.50, 15,
     ("offal", dict(body="#8E4A4A", dark="#6B3434", second="#C08A6A")),
     "Cleaned properly. Sambal hati, the underrated one."),

    # ---------------- NON-HALAL / PORK ----------------
    ("pork-belly", "Pork Belly (Samchan)", "Pork Belly", "nonhalal", "≈ 500g", 22.00, 17.00, 15,
     ("meatslab", dict(body="#D9847E", dark="#B05F59", fat="#F7EDE4", layers=True)),
     "Three-layer cut. Braise it, roast it, or siu yuk."),
    ("pork-ribs", "Pork Ribs", "Pork Ribs", "nonhalal", "≈ 600g", 26.00, 20.00, 12,
     ("ribs", dict(body="#CE7A74", dark="#A55852", bone="#F5EDE2")),
     "Meaty prime ribs, cut into serving pieces."),
    ("pork-loin", "Pork Loin", "Pork Loin", "nonhalal", "≈ 500g", 20.00, 15.50, 12,
     ("meatslab", dict(body="#DE9089", dark="#B56A63", fat="#F7EDE4", layers=False)),
     "Lean and tender. Good for chops and stir-fry."),
    ("minced-pork", "Minced Pork", "Minced Pork", "nonhalal", "≈ 500g", 18.00, 13.50, 15,
     ("minced", dict(body="#D9847E", dark="#AE5F59", light="#EDA69F")),
     "Freshly minced, not frozen. Dumplings and meatballs."),
    ("pork-trotter", "Pork Trotter", "Pork Trotter", "nonhalal", "≈ 800g", 16.00, 12.00, 10,
     ("trotter", dict(body="#E0A79E", dark="#B4786F", hoof="#8A6558")),
     "Cleaned and chopped. Vinegar pork trotter, the classic."),
    ("lap-cheong", "Lap Cheong", "Chinese Sausage", "nonhalal", "≈ 300g", 24.00, 19.00, 12,
     ("sausage", dict(body="#A83E34", dark="#7E2A22", tie="#D9C0A0")),
     "Sweet, dried and firm. Slice into claypot rice."),
]
